services:
  - type: web
    name: finalist-api-v2
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://finalist-v1.vercel.app
      - key: BACKEND_URL
        value: https://finalist-api-v2.onrender.com
