require('dotenv').config();
const mongoose = require('mongoose');
const Problem = require('./models/Problem');

const problemsBatch4 = [
  // --- THE 5 BASICS (Mixed Topics) ---
  {
    title: "Fibonacci Number",
    difficulty: "Basic",
    description: "The Fibonacci numbers, commonly denoted F(n) form a sequence, called the Fibonacci sequence, such that each number is the sum of the two preceding ones, starting from 0 and 1. Given n, calculate F(n).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n) or O(1)",
    examples: [
      { input: "n = 2", output: "1", explanation: "F(2) = F(1) + F(0) = 1 + 0 = 1." },
      { input: "n = 3", output: "2", explanation: "F(3) = F(2) + F(1) = 1 + 1 = 2." },
      { input: "n = 4", output: "3", explanation: "F(4) = F(3) + F(2) = 2 + 1 = 3." }
    ]
  },
  {
    title: "Search in a Binary Search Tree",
    difficulty: "Basic",
    description: "You are given the root of a binary search tree (BST) and an integer val. Find the node in the BST that the node's value equals val and return the subtree rooted with that node. If such a node does not exist, return null.",
    timeComplexity: "O(H)",
    spaceComplexity: "O(1)",
    examples: [
      { input: "root = [4,2,7,1,3], val = 2", output: "[2,1,3]", explanation: "The node with value 2 is found and its subtree is returned." },
      { input: "root = [4,2,7,1,3], val = 5", output: "[]", explanation: "A node with value 5 does not exist." },
      { input: "root = [5], val = 5", output: "[5]", explanation: "The root itself is the target." }
    ]
  },
  {
    title: "Power of Two",
    difficulty: "Basic",
    description: "Given an integer n, return true if it is a power of two. Otherwise, return false. An integer n is a power of two, if there exists an integer x such that n == 2^x.",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    examples: [
      { input: "n = 1", output: "true", explanation: "2^0 = 1." },
      { input: "n = 16", output: "true", explanation: "2^4 = 16." },
      { input: "n = 3", output: "false", explanation: "3 is not a power of two." }
    ]
  },
  {
    title: "Convert Sorted Array to Binary Search Tree",
    difficulty: "Basic",
    description: "Given an integer array nums where the elements are sorted in ascending order, convert it to a height-balanced binary search tree.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(log n)",
    examples: [
      { input: "nums = [-10,-3,0,5,9]", output: "[0,-3,9,-10,null,5]", explanation: "The array is converted into a balanced BST." },
      { input: "nums = [1,3]", output: "[3,1]", explanation: "1 is the left child of 3." },
      { input: "nums = [0]", output: "[0]", explanation: "A single element array becomes a single node tree." }
    ]
  },
  {
    title: "Middle of the Linked List",
    difficulty: "Basic",
    description: "Given the head of a singly linked list, return the middle node of the linked list. If there are two middle nodes, return the second middle node.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    examples: [
      { input: "head = [1,2,3,4,5]", output: "[3,4,5]", explanation: "The middle node of the list is node 3." },
      { input: "head = [1,2,3,4,5,6]", output: "[4,5,6]", explanation: "Since the list has two middle nodes with values 3 and 4, we return the second one." },
      { input: "head = [1]", output: "[1]", explanation: "The middle of a single node list is the node itself." }
    ]
  },

  // --- THE 15 MIXED ---
  {
    title: "Merge Strings Alternately",
    difficulty: "Easy",
    description: "You are given two strings word1 and word2. Merge the strings by adding letters in alternating order, starting with word1. If a string is longer than the other, append the additional letters onto the end of the merged string.",
    timeComplexity: "O(n + m)",
    spaceComplexity: "O(n + m)",
    examples: [
      { input: "word1 = \"abc\", word2 = \"pqr\"", output: "\"apbqcr\"", explanation: "The merged string will be merged as so: a p b q c r." },
      { input: "word1 = \"ab\", word2 = \"pqrs\"", output: "\"apbqrs\"", explanation: "Notice that as word2 is longer, \"rs\" is appended to the end." },
      { input: "word1 = \"abcd\", word2 = \"pq\"", output: "\"apbqcd\"", explanation: "Notice that as word1 is longer, \"cd\" is appended to the end." }
    ]
  },
  {
    title: "Find the Difference",
    difficulty: "Easy",
    description: "You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    examples: [
      { input: "s = \"abcd\", t = \"abcde\"", output: "\"e\"", explanation: "'e' is the letter that was added." },
      { input: "s = \"\", t = \"y\"", output: "\"y\"", explanation: "'y' is the only letter in t." },
      { input: "s = \"a\", t = \"aa\"", output: "\"a\"", explanation: "An extra 'a' was added." }
    ]
  },
  {
    title: "Contains Duplicate II",
    difficulty: "Easy",
    description: "Given an integer array nums and an integer k, return true if there are two distinct indices i and j in the array such that nums[i] == nums[j] and abs(i - j) <= k.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(k)",
    examples: [
      { input: "nums = [1,2,3,1], k = 3", output: "true", explanation: "nums[0] == nums[3] and abs(0 - 3) = 3 <= 3." },
      { input: "nums = [1,0,1,1], k = 1", output: "true", explanation: "nums[2] == nums[3] and abs(2 - 3) = 1 <= 1." },
      { input: "nums = [1,2,3,1,2,3], k = 2", output: "false", explanation: "The nearest duplicate is 3 indices away, which is > k." }
    ]
  },
  {
    title: "Ransom Note",
    difficulty: "Easy",
    description: "Given two strings ransomNote and magazine, return true if ransomNote can be constructed by using the letters from magazine and false otherwise. Each letter in magazine can only be used once in ransomNote.",
    timeComplexity: "O(m + n)",
    spaceComplexity: "O(1)",
    examples: [
      { input: "ransomNote = \"a\", magazine = \"b\"", output: "false", explanation: "'a' is not in the magazine." },
      { input: "ransomNote = \"aa\", magazine = \"ab\"", output: "false", explanation: "Magazine only has one 'a'." },
      { input: "ransomNote = \"aa\", magazine = \"aab\"", output: "true", explanation: "Magazine has enough 'a's." }
    ]
  },
  {
    title: "Is Subsequence",
    difficulty: "Easy",
    description: "Given two strings s and t, return true if s is a subsequence of t, or false otherwise.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    examples: [
      { input: "s = \"abc\", t = \"ahbgdc\"", output: "true", explanation: "\"abc\" appears in \"ahbgdc\" in the same relative order." },
      { input: "s = \"axc\", t = \"ahbgdc\"", output: "false", explanation: "'x' is missing from the target string." },
      { input: "s = \"\", t = \"ahbgdc\"", output: "true", explanation: "An empty string is a subsequence of any string." }
    ]
  },
  {
    title: "Search a 2D Matrix II",
    difficulty: "Medium",
    description: "Write an efficient algorithm that searches for a value target in an m x n integer matrix matrix. Integers in each row are sorted in ascending from left to right, and integers in each column are sorted in ascending from top to bottom.",
    timeComplexity: "O(m + n)",
    spaceComplexity: "O(1)",
    examples: [
      { input: "matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], target = 5", output: "true", explanation: "5 is located in the second row, second column." },
      { input: "matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], target = 20", output: "false", explanation: "20 is not found in the matrix." },
      { input: "matrix = [[-1]], target = -1", output: "true", explanation: "Single element matrix search." }
    ]
  },
  {
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    description: "Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.",
    timeComplexity: "O(H + k)",
    spaceComplexity: "O(H)",
    examples: [
      { input: "root = [3,1,4,null,2], k = 1", output: "1", explanation: "The 1st smallest element is 1." },
      { input: "root = [5,3,6,2,4,null,null,1], k = 3", output: "3", explanation: "The 3rd smallest element is 3." },
      { input: "root = [2,1,3], k = 2", output: "2", explanation: "The 2nd smallest element is 2." }
    ]
  },
  {
    title: "Construct Binary Tree from Inorder and Postorder Traversal",
    difficulty: "Medium",
    description: "Given two integer arrays inorder and postorder where inorder is the inorder traversal of a binary tree and postorder is the postorder traversal of the same tree, construct and return the binary tree.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    examples: [
      { input: "inorder = [9,3,15,20,7], postorder = [9,15,7,20,3]", output: "[3,9,20,null,null,15,7]", explanation: "The tree is correctly reconstructed using the traversal arrays." },
      { input: "inorder = [-1], postorder = [-1]", output: "[-1]", explanation: "A single node tree." },
      { input: "inorder = [1,2], postorder = [2,1]", output: "[1,null,2]", explanation: "A right-heavy tree of two nodes." }
    ]
  },
  {
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    description: "Given the root of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    examples: [
      { input: "root = [3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]", explanation: "Each level's nodes are grouped in their own arrays." },
      { input: "root = [1]", output: "[[1]]", explanation: "Single node returns a single level." },
      { input: "root = []", output: "[]", explanation: "Empty tree returns empty array." }
    ]
  },
  {
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    description: "Given a string s, find the length of the longest substring without repeating characters.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(min(m, n))",
    examples: [
      { input: "s = \"abcabcbb\"", output: "3", explanation: "The answer is \"abc\", with the length of 3." },
      { input: "s = \"bbbbb\"", output: "1", explanation: "The answer is \"b\", with the length of 1." },
      { input: "s = \"pwwkew\"", output: "3", explanation: "The answer is \"wke\", with the length of 3." }
    ]
  },
  {
    title: "Decode String",
    difficulty: "Medium",
    description: "Given an encoded string, return its decoded string. The encoding rule is: k[encoded_string], where the encoded_string inside the square brackets is being repeated exactly k times.",
    timeComplexity: "O(n * max(k))",
    spaceComplexity: "O(n)",
    examples: [
      { input: "s = \"3[a]2[bc]\"", output: "\"aaabcbc\"", explanation: "'a' is repeated 3 times, 'bc' is repeated 2 times." },
      { input: "s = \"3[a2[c]]\"", output: "\"accaccacc\"", explanation: "Nested brackets multiply the repetitions." },
      { input: "s = \"2[abc]3[cd]ef\"", output: "\"abcabccdcdcdef\"", explanation: "Plain text 'ef' remains unaffected." }
    ]
  },
  {
    title: "Unique Paths",
    difficulty: "Medium",
    description: "There is a robot on an m x n grid. The robot is initially located at the top-left corner. The robot tries to move to the bottom-right corner. The robot can only move either down or right at any point in time. Return the number of possible unique paths.",
    timeComplexity: "O(m * n)",
    spaceComplexity: "O(n)",
    examples: [
      { input: "m = 3, n = 7", output: "28", explanation: "There are 28 unique ways to navigate a 3x7 grid." },
      { input: "m = 3, n = 2", output: "3", explanation: "Right-Down-Down, Down-Right-Down, or Down-Down-Right." },
      { input: "m = 1, n = 1", output: "1", explanation: "No moves required, only 1 path." }
    ]
  },
  {
    title: "Word Search",
    difficulty: "Medium",
    description: "Given an m x n grid of characters board and a string word, return true if word exists in the grid. The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring.",
    timeComplexity: "O(m * n * 3^L)",
    spaceComplexity: "O(L)",
    examples: [
      { input: "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\"", output: "true", explanation: "The snake-like path finds the target word." },
      { input: "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"SEE\"", output: "true", explanation: "The word starts at the bottom row and moves up." },
      { input: "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCB\"", output: "false", explanation: "You cannot reuse cells you have already visited." }
    ]
  },
  {
    title: "N-Queens",
    difficulty: "Hard",
    description: "The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other. Given an integer n, return all distinct solutions to the n-queens puzzle.",
    timeComplexity: "O(N!)",
    spaceComplexity: "O(N^2)",
    examples: [
      { input: "n = 4", output: "[[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]", explanation: "There exist two distinct solutions to the 4-queens puzzle." },
      { input: "n = 1", output: "[[\"Q\"]]", explanation: "A 1x1 board has only 1 solution." },
      { input: "n = 2", output: "[]", explanation: "It is impossible to place 2 queens on a 2x2 board safely." }
    ]
  },
  {
    title: "Longest Valid Parentheses",
    difficulty: "Hard",
    description: "Given a string containing just the characters '(' and ')', return the length of the longest valid (well-formed) parentheses substring.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
    examples: [
      { input: "s = \"(()\"", output: "2", explanation: "The longest valid parentheses substring is \"()\"." },
      { input: "s = \")()())\"", output: "4", explanation: "The longest valid parentheses substring is \"()()\"." },
      { input: "s = \"\"", output: "0", explanation: "An empty string has a valid length of 0." }
    ]
  }
];

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

mongoose.connect(process.env.MONGO_URI)
  .then(async () => {
    console.log("Connected to MongoDB. Preparing Batch 4...");
    
    // Auto-increment logic
    const lastProblem = await Problem.findOne().sort('-problemNumber');
    let nextNumber = (lastProblem && lastProblem.problemNumber) ? lastProblem.problemNumber + 1 : 1;
    
    console.log(`Current max problemNumber is ${nextNumber - 1}. Starting Batch 4 from #${nextNumber}...`);

    shuffleArray(problemsBatch4);
    
    problemsBatch4.forEach(problem => {
        problem.problemNumber = nextNumber;
        nextNumber++;
    });
    
    try {
      await Problem.insertMany(problemsBatch4);
      console.log(`✅ Successfully seeded ${problemsBatch4.length} new mixed problems!`);
    } catch (err) {
      console.error("❌ Error inserting problems:", err);
    }
    
    process.exit(0);
  })
  .catch(err => {
    console.error("Database connection error:", err);
    process.exit(1);
  });